# This is a basic workflow to help you get started with Actions
name: First Workflow
# Controls when the workflow will run 
on: workflow_dispatch #Allows manual triggering of workflow      

jobs: 
  first-job: #the job name can be anything
    runs-on: ubuntu-latest #environment to run on. e.g. windows, ubuntu, mac
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Print greeting 
        run: echo "Hello world" #output a message to command line
      - name: Print goodbye
        run: echo "done bye"

 
